# Generated by Django 6.0.4 on 2026-04-18 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "georef_show_centerline",
                    models.BooleanField(
                        default=False, verbose_name="show centerline by default"
                    ),
                ),
                (
                    "georef_context_images",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("ghost", "Ghost"),
                            ("clickable", "Clickable with popups"),
                        ],
                        default="ghost",
                        max_length=16,
                        verbose_name="context image display",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
