# Generated by Django 6.0.4 on 2026-05-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_subjectmappingactivitygroup"),
        ("images", "0050_subjectmappingactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectmappingactivity",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="The activity group this activity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="activity.subjectmappingactivitygroup",
            ),
        ),
    ]
