# Generated by Django 6.0.4 on 2026-06-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0055_sitesettings_home_feed_item_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageoftheday",
            name="note_html",
            field=models.TextField(
                blank=True, editable=False, help_text="Cached rendered HTML of note"
            ),
        ),
    ]
