# Generated by Django 6.0.6 on 2026-07-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0058_collectionstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
