# Generated by Django 6.0.3 on 2026-03-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0008_address_business_occupation_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="suffix",
            field=models.CharField(
                blank=True, help_text="e.g. Jr., Sr., III", max_length=50
            ),
        ),
    ]
