# Generated by Django 6.0.4 on 2026-06-30 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0016_backfill_representative_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="description",
        ),
    ]
