# Generated by Django 6.0.7 on 2026-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0018_subject_title_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikidataitem",
            name="demolished",
            field=models.DateField(
                blank=True,
                help_text="Date of demolition/dissolution (Wikidata P576)",
                null=True,
            ),
        ),
    ]
